cat /etc/cupshelpers/preferreddrivers.xml
cat /etc/xml/libdbus-1-dev.xml
cat /etc/xml/polkitd.xml
cat /etc/xml/docbook-xml.xml
cat /etc/xml/xml-core.xml
cat /etc/xml/sgml-data.xml
cat /etc/thermald/thermal-cpu-cdev-order.xml
cat /etc/xdg/openbox/rc.xml
cat /etc/xdg/openbox/menu.xml
cat /etc/ImageMagick-6/delegates.xml
cat /etc/ImageMagick-6/policy-open.xml
cat /etc/ImageMagick-6/type-apple.xml
cat /etc/ImageMagick-6/log.xml
cat /etc/ImageMagick-6/colors.xml
cat /etc/ImageMagick-6/thresholds.xml
cat /etc/ImageMagick-6/type-ghostscript.xml
cat /etc/ImageMagick-6/quantization-table.xml
cat /etc/ImageMagick-6/policy.xml
cat /etc/ImageMagick-6/type.xml
cat /etc/ImageMagick-6/policy-limited.xml
cat /etc/ImageMagick-6/policy-secure.xml
cat /etc/ImageMagick-6/type-dejavu.xml
cat /etc/ImageMagick-6/mime.xml
cat /etc/ImageMagick-6/policy-debian.xml
cat /etc/ImageMagick-6/type-urw-base35.xml
cat /etc/ImageMagick-6/type-windows.xml
cat /etc/ImageMagick-6/coder.xml
cat /etc/ImageMagick-6/policy-websafe.xml
cat /etc/ImageMagick-6/magic.xml
